forbidden-modules:
  - proxy_module
  - proxy_connect_module
  - proxy_ftp_module
  - proxy_http_module
  - proxy_fcgi_module
  - proxy_scgi_module
  - proxy_ajp_module
  - proxy_balancer_module
  - proxy_express_module
  - proxy_wstunnel_module
  - proxy_fdpass_module
  - mime_module

weekly-log-rotation: '13'